include: 'Templates/build_dotnet_template.gitlab-ci.yml'
#just
variables:
  VERSION: '1.0'
  CONFIG: 'Release'
  PROJECT_PATH: 'MovieCatalogAPI/MovieCatalogAPI.csproj'  
  TESTS_PATH: 'MovieCatalogAPI.Tests/MovieCatalogAPI.Tests.csproj'
  RELEASE_BUILD_PATH: 'app/Release/'
  DEPLOY_FOLDER: '/Builds'
  LOG_PATH: 'app/Tests/logs'

stages:
  - test
  - build_prod
  - deploy

test_job:
  image: mcr.microsoft.com/dotnet/sdk:6.0-alpine-amd64
  stage: test
  only:
    - branches
  script:
    - dotnet test $TESTS_PATH --Diag $LOG_PATH/test_logs.txt
  services:
    - name: redis:alpine
  artifacts:
    expire_in: 1 month
    when: 
      - always 
    paths:
      - '$LOG_PATH/test_logs.txt'  # saving logs

build_app:
  image: mcr.microsoft.com/dotnet/sdk:6.0-alpine-amd64
  stage: build_prod
  needs: ["test_job"]
  only:
    - master
  variables:
    VERSION_NUMBER: "0.1"
    CONFIG: "Release"
  script:
    - dotnet build $PROJECT_PATH -c $CONFIG
    - dotnet publish $PROJECT_PATH -c $CONFIG --os linux-x64 -o $RELEASE_BUILD_PATH --version-suffix $VERSION_NUMBER 
    - ls $RELEASE_BUILD_PATH
  artifacts:
    expire_in: 1 week
    when: 
      - on_success 
    paths:
      - '$RELEASE_BUILD_PATH'  # saving exe to copy to deploy folder


#docker build
build_docker:
  image: docker
  stage: build_prod
  needs: ["build_app"]
  only:
    - master
  script:
    - docker login gitlab.kupriyanov.space:5050
    - docker build -t gitlab.kupriyanov.space:5050/slava_chaunin/webapi-aspnet-movie-catalog .
    - docker push gitlab.kupriyanov.space:5050/slava_chaunin/webapi-aspnet-movie-catalog

deploy_job:
  stage: deploy
  needs: ["test_job","build_app"]
  only:
    - master
  script:
    - echo "TODO"
    #get container from container registry
    #docker up
    # login before script
    # add to enviroment variables ASPNETCORE_URLS


  dependencies:
    - build_app
    - test_job
