include:
  - local: 'Templates/dotnet_build_template.yml'

variables:
  VERSION: '0.1'
  CONFIG: 'Release'
  PROJECT_PATH: '/builds/slava_chaunin/webapi-aspnet-movie-catalog/MovieCatalogAPI/MovieCatalogAPI.csproj'  
  TESTS_PATH: '/builds/slava_chaunin/webapi-aspnet-movie-catalog/MovieCatalogAPI.Tests/MovieCatalogAPI.Tests.csproj'
  RELEASE_BUILD_PATH: 'app/Release/'
  DEPLOY_FOLDER: 'MovieCatalogAPI'
  LOG_PATH: 'app/Tests/logs'
  TARGET_OS: "linux-x64"
  DATABASE_CONNECTION_STRING_TEST: "Server=host.docker.internal;Database=MovieDB;UserID=postgres;Password=2003;"
  DATABASE_CONNECTION_STRING_PROD: "Server=localhost;Database=MovieDB;UserID=postgres;Password=2003;"

stages:
  - build
  - test
  - build_prod
  - deploy

build_job:
  image: mcr.microsoft.com/dotnet/sdk:6.0-jammy-amd64
  stage: build
  script:
    - dotnet format --diagnostics $PROJECT_PATH
    - dotnet build $PROJECT_PATH  -c $CONFIG --os $OS --version-suffix $VERSION

test_job:
  image: mcr.microsoft.com/dotnet/sdk:6.0-jammy-amd64
  stage: test
  variables:
    ConnectionStrings__Default: $DATABASE_CONNECTION_STRING
  only:
    - branches
  script:
    - dotnet test $TESTS_PATH --logger "trx;logfilename=testResults.trx"
    - mkdir -p $LOG_PATH
    - mv /builds/slava_chaunin/webapi-aspnet-movie-catalog/MovieCatalogAPI.Tests/TestResults/testResults.trx $LOG_PATH
  services:
    - name: redis:alpine
  artifacts:
    paths:
      - $LOG_PATH  # saving logs

build_app:
  extends: .build
  stage: build_prod
  only:
    - master
  variables:
    PROJECT_PATH: $PROJECT_PATH
    VERSION_NUMBER: $VERSION
    CONFIG: $CONFIG
    OS: $TARGET_OS
    BUILD_PATH: $RELEASE_BUILD_PATH"
  after_script:
    - ls $RELEASE_BUILD_PATH


#docker build
build_docker:
  image: docker
  stage: build_prod
  needs: ["build_app"]
  only:
    - master
  script:
    - docker login gitlab.kupriyanov.space:5050
    - docker build -t gitlab.kupriyanov.space:5050/slava_chaunin/webapi-aspnet-movie-catalog .
    - docker push gitlab.kupriyanov.space:5050/slava_chaunin/webapi-aspnet-movie-catalog

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - echo "TODO"
    #get container from container registry
    #docker up
    # login before script
    # add to enviroment variables ASPNETCORE_URLS


  dependencies:
    - build_app
    - test_job
